services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ercot
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ercot"]
      interval: 5s
      timeout: 5s
      retries: 10
  preprocess:
    image: shifty
    env_file:
      - .env
    environment:
      PYTHONPATH: /preprocess:/opt
    volumes:
      - ./preprocess:/preprocess
      - ./data:/data
      - ./shared:/opt/shared:ro
    working_dir: /preprocess
    profiles: ["tools"]
    command: python
  compute:
    build: ./compute
    image: shifty
    container_name: compute
    env_file:
      - .env
    environment:
      PYTHONPATH: /api:/compute:/opt
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./compute:/compute
      - ./shared:/opt/shared:ro
      - ./ercot_ingest:/ercot_ingest
      - ./data:/data
    command: python
  api:
    image: shifty
    container_name: api
    env_file:
      - .env
    environment:
      PYTHONPATH: /api:/compute:/opt
    working_dir: /api
    depends_on:
      db:
        condition: service_healthy
      compute:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - ./compute:/compute
      - ./api:/api
      - ./shared:/opt/shared:ro
      - ./data:/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  ercot-proxy:     # "deploys to cloudflare"
    image: node:20-alpine
    container_name: ercot-proxy
    working_dir: /ercot_ingest/proxy
    volumes:
      - ./ercot_ingest/proxy:/ercot_ingest/proxy
      - proxy-wrangler-config:/root/.config/.wrangler
    env_file:
      - .env
    profiles: ["tools"]
    entrypoint: ["npx", "--yes", "wrangler@latest"]
    command: ["--help"]

  # TODO: replace w/ cron
  updater:
      build: ./compute
      image: shifty
      container_name: updater
      env_file:
        - .env
      environment:
        PYTHONPATH: /api:/compute:/opt
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - ./ercot_ingest:/ercot_ingest
        - ./shared:/opt/shared:ro
      command: python /ercot_ingest/live_updater.py
      restart: unless-stopped

volumes:
  pgdata:
