#!/usr/bin/env python3
"""Vendor Inter + JetBrains Mono into public/fonts/ as self-hosted woff2.

Run from web/:  python3 scripts/fetch-fonts.py

Self-hosted rather than a Google Fonts @import so the app has no render-blocking
third-party request and no FOUT on a console that is mostly numbers.

Subsets: latin, latin-ext and greek. Greek is not optional -- the UI renders
gamma/Delta/lambda/mu/rho/Sigma in the model panels, and a latin-only subset
would silently fall back mid-line. A final "symbols" face carries the arrows and
math operators (-> <- <-> ~= <= >= prop sqrt) that Google's latin range omits.
Dingbats and emoji (warning sign, play, pause, calendar) are left to the system
font, exactly as they were under Barlow.
"""
import os
import re
import urllib.parse
import urllib.request

OUT_DIR = "public/fonts"
CSS_OUT = "src/fonts.css"

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Variable axes, so one file per subset covers every weight the UI asks for
# instead of a separate download per discrete weight.
FAMILIES = [
    ("Inter", "Inter", "100..900", "100 900"),
    ("JetBrains Mono", "JetBrains Mono", "100..800", "100 800"),
]

KEEP_SUBSETS = {"latin", "latin-ext", "greek"}

# Glyphs the app uses that fall outside Google's latin/latin-ext/greek ranges.
SYMBOLS = "←→↔≈≤≥∝√"
SYMBOL_RANGE = ("U+2190, U+2192, U+2194, U+221A, U+221D, "
                "U+2248, U+2264, U+2265")


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


def slug(name):
    return name.lower().replace(" ", "-")


# Google emits "/* latin */" ahead of each @font-face; pair comment with block.
BLOCK_RE = re.compile(
    r"/\*\s*([a-z0-9\-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", re.S)


def parse(css):
    for m in BLOCK_RE.finditer(css):
        subset, body = m.group(1), m.group(2)
        url = re.search(r"url\((https://[^)]+)\)", body)
        rng = re.search(r"unicode-range:\s*([^;]+);", body)
        if not (url and rng):
            continue
        yield subset, url.group(1), rng.group(1).strip()


def face(family, weight, path, rng):
    return (
        "@font-face {\n"
        f"  font-family: '{family}';\n"
        "  font-style: normal;\n"
        f"  font-weight: {weight};\n"
        "  font-display: swap;\n"
        f"  src: url('{path}') format('woff2');\n"
        f"  unicode-range: {rng};\n"
        "}\n"
    )


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    blocks, total = [], 0

    for css_name, google_name, axis, weight_decl in FAMILIES:
        q = urllib.parse.urlencode({
            "family": f"{google_name}:wght@{axis}",
            "display": "swap",
        })
        css = get(f"https://fonts.googleapis.com/css2?{q}")

        for subset, url, rng in parse(css):
            if subset not in KEEP_SUBSETS:
                continue
            fname = f"{slug(css_name)}-{subset}.woff2"
            blob = get(url, binary=True)
            with open(os.path.join(OUT_DIR, fname), "wb") as f:
                f.write(blob)
            total += len(blob)
            blocks.append(face(css_name, weight_decl, f"/fonts/{fname}", rng))
            print(f"  {css_name:16} {subset:10} {len(blob)/1024:6.1f} KB")

        # Symbols face. Static 400/700 -- Google will not subset a variable axis
        # via `text=`, and these few glyphs do not need intermediate weights.
        for weight in (400, 700):
            q = urllib.parse.urlencode({
                "family": f"{google_name}:wght@{weight}",
                "text": SYMBOLS,
            })
            sub_css = get(f"https://fonts.googleapis.com/css2?{q}")
            m = re.search(r"url\((https://[^)]+)\)\s*format\('woff2'\)", sub_css)
            if not m:
                print(f"  !! no symbols face for {css_name} {weight}")
                continue
            fname = f"{slug(css_name)}-{weight}-symbols.woff2"
            blob = get(m.group(1), binary=True)
            with open(os.path.join(OUT_DIR, fname), "wb") as f:
                f.write(blob)
            total += len(blob)
            blocks.append(face(css_name, str(weight), f"/fonts/{fname}", SYMBOL_RANGE))
            print(f"  {css_name:16} {'symbols':10} {weight}  {len(blob)/1024:6.1f} KB")

    header = (
        "/* Generated by scripts/fetch-fonts.py -- do not edit by hand.\n"
        "   Self-hosted Inter + JetBrains Mono (latin, latin-ext, greek, symbols). */\n\n"
    )
    with open(CSS_OUT, "w") as f:
        f.write(header + "\n".join(blocks))
    print(f"\n{len(blocks)} faces, {total/1024:.1f} KB total -> {CSS_OUT}")


if __name__ == "__main__":
    main()
