import pypsa
import pandas as pd
import numpy as np
from fragility import compute_fragility, fragility_diagnostics, fragility_plot

n = pypsa.Network("/data/processed/Texas2k_series25_case1_summerpeak.nc")

"""
Populate load time-series from static values
file has no load time-series at all, just static values. This is how TAMU ships the Texas2k case

have to populate loads_t.p_set from the static loads.p_set values
n.optimize() reads from loads_t.p_set (the time-varying table), not
loads.p_set (the static column).
"""

n.loads_t.p_set = pd.DataFrame(
    [n.loads.p_set.values],
    index=n.snapshots,
    columns=n.loads.index
)

# Apply marginal costs
mc = pd.read_csv("/data/processed/marginal_costs.csv", index_col=0)
n.generators['marginal_cost'] = n.generators.index.map(mc['marginal_cost']).fillna(0)

"""Realistic summer peak availability (5 PM August)
p_max_pu: "maximum power output as a fraction of nameplate capacity." [0, 1] per-unit mulitiplier
e.g for 100 MW wind farm: p_nom = 100; p_max_pu = 1 -> 100 MW right now, p_max_pu =.2 -> 20 MW right now

because Texas2k there's no time series for availability ?
every generator defaults p_max_pu = 1.0 - run at full nameplate.
so the solver thought every generator could run at full nameplate.

Dispatch output at p_max_pu 1.0:
dispatch by fuel - which is way off, no way max is generated by wind, solar, battery
because merit order p_max_pu 1.0 is to max out the cheapest $0 generation
carrier
wind       37404.0
solar      29084.0
battery    13768.0
nuclear     4302.0
gas          757.0
hydro        444.0
biomass        0.0
coal           0.0
other          0.0
oil            0.0


Rough placeholder estimates of typical ERCOT conditions at 5 PM in August:
TODO: real data from ERCOT MIS
NP4-732-CD: real-time wind actuals (per zone)
NP4-745-CD: real-time solar actuals

Adding the cf_summer_peak factors changed dispatch composition:

gas        47804.0
solar      21016.0
wind        8365.0
nuclear     4731.0
battery     3567.0
hydro        276.0
biomass        0.0
coal           0.0
other          0.0
oil            0.0

but now the pricing is off; uniform everywhere: LMP min = mean = max = 28.55

every single bus has the exact same price. That means no transmission
congestion anywhere, which is unrealistic for Texas in August. TAMU network has
enough line capacity that nothing was constraining the optimum - missing shadow
prices and can't calculate fragility.

Fix: de-rate transformers capacities by 5% (.95), lines by 10% (.90)
n.lines['s_nom'] = n.lines['s_nom'] * 0.9
n.transformers['s_nom'] = n.transformers['s_nom'] * 0.95


Lastly, even with "forced congestion" by de-rating, PyPSA wasn't writing shadow
prices back to network object. Needed to set assign_all_duals=True flag on
n.optimize().

"""

cf_summer_peak = {
    'wind': 0.20,      # ERCOT wind typically 15-30% at peak
    'solar': 0.65,     # still producing but sun dropping
    'battery': 0.25,   # partial SOC, limited duration
    'nuclear': 0.95,
    'hydro': 0.50,
    'coal': 0.90,      # available but not forced on
    'gas': 0.90,
    'oil': 0.80,
    'biomass': 0.80,
    'other': 0.80,
}

for carrier, cf in cf_summer_peak.items():
    mask = n.generators.carrier == carrier
    n.generators.loc[mask, 'p_max_pu'] = cf


# derate by 10% lines, transformers 5%
# Force binding constraints for testing
# doing this to artificially trigger LMP variation and verify model behavior.
n.lines['s_nom'] = n.lines['s_nom'] * 0.9
n.transformers['s_nom'] = n.transformers['s_nom'] * 0.95

# Lock capacity (operational dispatch only)
n.generators['p_nom_extendable'] = False
n.lines['s_nom_extendable'] = False

# Patch zero-resistance lines (PTDF numerical stability)
n.lines.loc[n.lines.r == 0, 'r'] = 1e-4

#
# Solve DC-OPF
#
status, cond = n.optimize(solver_name="highs", assign_all_duals=True)
print(f"Status: {status}, {cond}")

# Sanity checks
gen = n.generators_t.p.iloc[0].sum()
load = n.loads_t.p_set.iloc[0].sum()
lmps = n.buses_t.marginal_price.iloc[0]

print(f"\nGen: {gen:.0f} MW | Load: {load:.0f} MW | Balance: {gen - load:+.1f}")
print(f"LMP: min={lmps.min():.2f}, mean={lmps.mean():.2f}, max={lmps.max():.2f}")
print(f"LMP p5/p50/p95: {lmps.quantile([0.05, 0.5, 0.95]).round(2).values}")

print("\nDispatch by fuel:")
dispatch = n.generators.assign(p=n.generators_t.p.iloc[0]).groupby('carrier')['p'].sum().sort_values(ascending=False)
print(dispatch.round(0))



# ---- PTDF on current topology ----
n.determine_network_topology()
sub = n.sub_networks.obj.iloc[0]
sub.calculate_PTDF()
ptdf_full = sub.PTDF # (n_branches, n_buses) = (lines + transformers, buses)
sub_buses = sub.buses_o  # ordered bus names for this sub-network


#
# FRAGILITY
#

fragility = compute_fragility(n, ptdf_full, sub_buses)
fragility_diagnostics(fragility)
fragility_plot(n, fragility)

#
# Top N-1 Contingency
# If any single line were to trip, which trip would cause the most stress?
#
# flow_post[line] = flow_base[line] + LODF[line, c] × flow_base[c]
#
import numpy as np
import pandas as pd

# ---- Compute LODF on current topology ----
sub.calculate_BODF()   # PyPSA uses BODF (same as LODF for single-line outages)
lodf_full = sub.BODF  # shape: (n_branches, n_branches)

# We only simulate line outages, not transformer outages
# (transformers are usually protected differently and we don't trip them for N-1)
n_lines_n = len(n.lines)
lodf_line_line = lodf_full[:n_lines_n, :n_lines_n]  # line outages affect lines only

# Base flows on lines
flow_base = n.lines_t.p0.iloc[0].reindex(n.lines.index).fillna(0).values
s_nom_line = n.lines['s_nom'].values

# For each candidate line outage, compute post-outage stress metric
def contingency_stress(outage_idx):
    """Return post-outage stress (sum of overloads) when line at outage_idx trips."""
    # Radial lines: BODF diagonal is -1, but outage would disconnect grid. Skip.
    if np.isnan(lodf_line_line[0, outage_idx]):
        return 0.0, None

    # Post-outage flows on all lines
    shift = lodf_line_line[:, outage_idx] * flow_base[outage_idx]
    flow_post = flow_base + shift
    flow_post[outage_idx] = 0.0  # tripped line carries no flow

    # Loading ratio for each line under the outage
    loading = np.abs(flow_post) / s_nom_line

    # Overload: how much each line exceeds its limit (0 if under)
    overload = np.maximum(loading - 1.0, 0.0)

    # Stress score: sum of overload percentages (could weight by MW instead)
    return overload.sum(), overload

# Rank all line outages by stress
stress_scores = []
for i, line in enumerate(n.lines.index):
    score, _ = contingency_stress(i)
    stress_scores.append((line, score))

stress_df = pd.DataFrame(stress_scores, columns=['line', 'stress']).set_index('line')
stress_df = stress_df.sort_values('stress', ascending=False)

print(f"\nTop 10 most dangerous N-1 contingencies:")
print(stress_df.head(10))

# For the top contingency, show what overloads
top_line = stress_df.index[0]
top_idx = list(n.lines.index).index(top_line)
_, overload_arr = contingency_stress(top_idx)
overload_series = pd.Series(overload_arr, index=n.lines.index)
newly_overloaded = overload_series[overload_series > 0].sort_values(ascending=False)

print(f"\nIf {top_line} trips (base flow: {flow_base[top_idx]:.0f} MW, s_nom: {s_nom_line[top_idx]:.0f} MW):")
print(f"  {len(newly_overloaded)} lines become overloaded")
print(f"  Top 5 newly-overloaded lines:")
print(newly_overloaded.head(5))
