import pypsa
import pandas as pd
import numpy as np

n = pypsa.Network("/data/processed/Texas2k_series25_case1_summerpeak.nc")

"""
Populate load time-series from static values
file has no load time-series at all, just static values. This is how TAMU ships the Texas2k case

have to populate loads_t.p_set from the static loads.p_set values
n.optimize() reads from loads_t.p_set (the time-varying table), not
loads.p_set (the static column).
"""

n.loads_t.p_set = pd.DataFrame(
    [n.loads.p_set.values],
    index=n.snapshots,
    columns=n.loads.index
)

# Apply marginal costs
mc = pd.read_csv("/data/processed/marginal_costs.csv", index_col=0)
n.generators['marginal_cost'] = n.generators.index.map(mc['marginal_cost']).fillna(0)

"""Realistic summer peak availability (5 PM August)
p_max_pu: "maximum power output as a fraction of nameplate capacity." [0, 1] per-unit mulitiplier
e.g for 100 MW wind farm: p_nom = 100; p_max_pu = 1 -> 100 MW right now, p_max_pu =.2 -> 20 MW right now

because Texas2k there's no time series for availability ?
every generator defaults p_max_pu = 1.0 - run at full nameplate.
so the solver thought every generator could run at full nameplate.

Dispatch output at p_max_pu 1.0:
dispatch by fuel - which is way off, no way max is generated by wind, solar, battery
because merit order p_max_pu 1.0 is to max out the cheapest $0 generation
carrier
wind       37404.0
solar      29084.0
battery    13768.0
nuclear     4302.0
gas          757.0
hydro        444.0
biomass        0.0
coal           0.0
other          0.0
oil            0.0


Rough placeholder estimates of typical ERCOT conditions at 5 PM in August:
TODO: real data from ERCOT MIS
NP4-732-CD: real-time wind actuals (per zone)
NP4-745-CD: real-time solar actuals

Adding the cf_summer_peak factors changed dispatch composition:

gas        47804.0
solar      21016.0
wind        8365.0
nuclear     4731.0
battery     3567.0
hydro        276.0
biomass        0.0
coal           0.0
other          0.0
oil            0.0

but now the pricing is off; uniform everywhere: LMP min = mean = max = 28.55

every single bus has the exact same price. That means no transmission
congestion anywhere, which is unrealistic for Texas in August. TAMU network has
enough line capacity that nothing was constraining the optimum - missing shadow
prices and can't calculate fragility.

Fix: de-rate transformers capacities by 5% (.95), lines by 10% (.90)
n.lines['s_nom'] = n.lines['s_nom'] * 0.9
n.transformers['s_nom'] = n.transformers['s_nom'] * 0.95


Lastly, even with "forced congestion" by de-rating, PyPSA wasn't writing shadow
prices back to network object. Needed to set assign_all_duals=True flag on
n.optimize().

"""

cf_summer_peak = {
    'wind': 0.20,      # ERCOT wind typically 15-30% at peak
    'solar': 0.65,     # still producing but sun dropping
    'battery': 0.25,   # partial SOC, limited duration
    'nuclear': 0.95,
    'hydro': 0.50,
    'coal': 0.90,      # available but not forced on
    'gas': 0.90,
    'oil': 0.80,
    'biomass': 0.80,
    'other': 0.80,
}

for carrier, cf in cf_summer_peak.items():
    mask = n.generators.carrier == carrier
    n.generators.loc[mask, 'p_max_pu'] = cf


# derate by 10% lines, transformers 5%
# Force binding constraints for testing
# doing this to artificially trigger LMP variation and verify model behavior.
n.lines['s_nom'] = n.lines['s_nom'] * 0.9
n.transformers['s_nom'] = n.transformers['s_nom'] * 0.95

# Lock capacity (operational dispatch only)
n.generators['p_nom_extendable'] = False
n.lines['s_nom_extendable'] = False

# Patch zero-resistance lines (PTDF numerical stability)
n.lines.loc[n.lines.r == 0, 'r'] = 1e-4

# Solve DC-OPF
status, cond = n.optimize(solver_name="highs", assign_all_duals=True)
print(f"Status: {status}, {cond}")

# Sanity checks
gen = n.generators_t.p.iloc[0].sum()
load = n.loads_t.p_set.iloc[0].sum()
lmps = n.buses_t.marginal_price.iloc[0]

print(f"\nGen: {gen:.0f} MW | Load: {load:.0f} MW | Balance: {gen - load:+.1f}")
print(f"LMP: min={lmps.min():.2f}, mean={lmps.mean():.2f}, max={lmps.max():.2f}")
print(f"LMP p5/p50/p95: {lmps.quantile([0.05, 0.5, 0.95]).round(2).values}")

print("\nDispatch by fuel:")
dispatch = n.generators.assign(p=n.generators_t.p.iloc[0]).groupby('carrier')['p'].sum().sort_values(ascending=False)
print(dispatch.round(0))


#
# FRAGILITY
#

# ---- PTDF on current topology ----
n.determine_network_topology()
sub = n.sub_networks.obj.iloc[0]
sub.calculate_PTDF()
ptdf_full = sub.PTDF # (n_branches, n_buses) = (lines + transformers, buses)
sub_buses = sub.buses_o  # ordered bus names for this sub-network

# ---- Gather shadow prices and line data ----
# Lines
mu_up_ln = n.lines_t.mu_upper.iloc[0].abs()
mu_lo_ln = n.lines_t.mu_lower.iloc[0].abs()
shadow_ln = (mu_up_ln + mu_lo_ln).reindex(n.lines.index).fillna(0).values
flow_ln = n.lines_t.p0.iloc[0].abs().reindex(n.lines.index).fillna(0).values
s_nom_ln = n.lines['s_nom'].values
headroom_ln = np.maximum(s_nom_ln - flow_ln, 1.0)  # floor at 1 MW to avoid divide-by-zero

# ---- Fragility: Σ PTDF² × shadow / headroom per bus ----
# PTDF is (n_lines, n_buses); we want per-bus sum over lines
# PTDF includes transformers; slice to lines
print(f"PTDF shape: {ptdf_full.shape}")
print(f"Number of lines: {len(n.lines)}")
print(f"Number of transformers: {len(n.transformers)}")
print(f"Sum: {len(n.lines) + len(n.transformers)}")


# Transformers
mu_up_tx = n.transformers_t.mu_upper.iloc[0].abs() if not n.transformers_t.mu_upper.empty else pd.Series(0.0, index=n.transformers.index)
mu_lo_tx = n.transformers_t.mu_lower.iloc[0].abs() if not n.transformers_t.mu_lower.empty else pd.Series(0.0, index=n.transformers.index)

shadow_tx = (mu_up_tx + mu_lo_tx).reindex(n.transformers.index).fillna(0).values
flow_tx = n.transformers_t.p0.iloc[0].abs().reindex(n.transformers.index).fillna(0).values
s_nom_tx = n.transformers['s_nom'].values
headroom_tx = np.maximum(s_nom_tx - flow_tx, 1.0)

# Stack: PTDF rows are [lines, transformers]
weights_full = np.concatenate([shadow_ln / headroom_ln, shadow_tx / headroom_tx])
fragility_vec = ((ptdf_full ** 2) * weights_full[:, np.newaxis]).sum(axis=0)
frag = pd.Series(fragility_vec, index=sub_buses, name='fragility')


print(f"\nFragility stats:")
print(frag.describe())
print(f"\nTop 10 most fragile buses:")
print(frag.sort_values(ascending=False).head(10))


# Concentration — how many buses are meaningfully fragile?
total_frag = frag.sum()
mean_frag = frag.mean()
p95 = frag.quantile(0.95)
p99 = frag.quantile(0.99)

print(f"Fragility: total={total_frag:.2f}, mean={mean_frag:.4f}, p95={p95:.4f}, p99={p99:.4f}")
print(f"Buses above p95 ({p95:.3f}): {(frag > p95).sum()}")
print(f"Buses above p99 ({p99:.3f}): {(frag > p99).sum()}")
print(f"Buses with fragility > 0.1: {(frag > 0.1).sum()}")
print(f"Buses with fragility > 0.01: {(frag > 0.01).sum()}")

# Concentration ratio — what fraction of total fragility is in the top 10 buses?
top10_share = frag.nlargest(10).sum() / total_frag
print(f"Top 10 buses hold {top10_share:.1%} of total fragility")



#
# PLOT
#
import matplotlib.pyplot as plt

# Build a dataframe with coords + fragility
frag_map = pd.DataFrame({
    'x': n.buses.loc[frag.index, 'x'],
    'y': n.buses.loc[frag.index, 'y'],
    'fragility': frag.values
}).dropna()

# Plot, log scale for readability
fig, ax = plt.subplots(figsize=(10, 8))
sc = ax.scatter(frag_map['x'], frag_map['y'],
                c=np.log10(frag_map['fragility'].clip(lower=1e-6)),
                cmap='plasma', s=3, alpha=0.7)
plt.colorbar(sc, label='log10(fragility)')

# Highlight the top-5 buses
top5 = frag.nlargest(5).index
ax.scatter(n.buses.loc[top5, 'x'], n.buses.loc[top5, 'y'],
           s=100, edgecolor='red', facecolor='none', linewidth=2,
           label='Top 5 most fragile')
ax.legend()
ax.set_title('Fragility map (log scale)')
plt.savefig('fragility_map.png', dpi=120)
plt.show()

