apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compute-runs
  namespace: ercotstress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
