"""Schemas served by the daily analysis and Brief routes."""
from models import (
    AnalysisConstraintRow, AnalysisConstraintsAvailableResponse,
    AnalysisConstraintsUnavailableResponse, AnalysisContributionTerm,
    AnalysisEsspGroupsAvailableResponse, AnalysisEsspGroupsUnavailableResponse,
    AnalysisSettlementPointMetadata, AnalysisSettlementPointsAvailableResponse,
    AnalysisSettlementPointsUnavailableResponse, BriefDayResponse,
    BriefDetailsResponse, BriefHeroShellResponse, BriefHeroStatsResponse,
    ChronicElementRow, ContextAvailableResponse, ContextUnavailableResponse,
    EsspGroup, ForecastMuAvailableResponse, ForecastMuRow,
    ForecastMuUnavailableResponse, GradeAvailableResponse, GradeHalfResponse,
    GradeHistoryAvailableResponse, GradeHistoryDayResponse,
    GradeHistoryHalfResponse, GradeHistoryUnavailableResponse,
    GradeUnavailableResponse, HeroAvailableResponse, HeroLatestResponse,
    HeroUnavailableAtHorizonResponse, HeroUnavailableResponse, NodeAnalysisAvailableResponse,
    NodeAnalysisUnavailableResponse, NodeMarketState, NodeStandoutRow,
    StandoutRow, StandoutsAvailableResponse, StandoutsUnavailableResponse,
    TopConstraintRow, TopConstraintsAvailableResponse,
    TopConstraintsUnavailableResponse, TopNodeRow, TopNodesAvailableResponse,
    TopNodesUnavailableResponse, VoltageClassRow,
)
